id: P87BAD483
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: de
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    b771b55d36b145d7929a527e4fcb8598:
      title: Advice for Hor Özer
      parent: Advice
    53033d0d08a34c82bf822de175b0f811:
      title: Advice for Palseng
      parent: Advice
    129999549d13413fadd76914c1275a84:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    e67b9190291c49689a336878f7afe92e:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    2f00b5802b1047cebb952d38a1b76cb4:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    c35db6eb68834c4b9986a8792f48fdcd:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    eb95117015194ebeb10da6c2ad7515df:
      title: An Instruction on the Great Perfection
      parent: Advice
    174dcc7bdc3a4ef8b97e751d066db811:
      title: Brief Dzogchen Instruction
      parent: Advice
    1a1a99ad61de4baf8b35502c6d1254ae:
      title: Direct Instruction
      parent: Advice
    93e27688b4ea434e9a982c7c61003d48:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    a2a4a8278d3b437cb874aba66007a355:
      title: Vajra Verses on the Natural State
      parent: Advice
    887068d633bf42348210b749bf047fe0:
      title: Advice for a King
      parent: Advice
    140f9d6a3fae4e05954b3d1be92cd02e:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    02a26a20c7354873822c21180054cd49:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    2652ed495d9e49cdb527d3af63835bb6:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    9f60d67f1fe746a2a262a368e7e32ffa:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    1464273a75a94e1da9b1fa9b0f0ffbad:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    462a2f433da44ded9dbcfed37544a585:
      title: A Liberating Reminder
      parent: Advice
    62a88ce80da94cd1ac6e5ba0bc926342:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    ee10da5d84e84eddbac050ec2b2bedc1:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    2d9dc375fe764d5c96bb8a313c5ee261:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    c021787167d74072a7d809d8556fc415:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    8372725add124c3d9f33dd708be97ba6:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    b1979f2c673a493fb84768dc376f9b84:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    361b939e7f734093bbf667a7f907b632:
      title: The Essence of Mind
      parent: Advice
    cabc19b6e810499a9bf719420a34f4b4:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    903555fb4fb843b3b43bed4a105e24d8:
      title: The Key Points of Trekchö
      parent: Advice
    10d52ef1081b49e597e7a5e6aaf74978:
      title: The Nature of Mind
      parent: Advice
    d42d0700667144bcbb11c33e6aa1cc58:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    3a93ee31fac74695bbe68f4a5325b776:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    0da11be40885492788b5d9900bf593eb:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    10bf493a18214b15a8423fe48c083bf3:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    e58f16f95fa344989aa4b0c2c2f0b586:
      title: The Five Wisdoms
      parent: Advice
    8d3185cb06464829baaa1dae791ef717:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    0180fb9e06be43e0b05c719993aa6167:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    a4a386f740704201a86be3894d6857ef:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    ced098c8fcea4a759e33cb8b07cef26f:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    25e02cc9cb0b4dc1a520ca7f8ccbee6f:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    c10602a644f9495f91a32d66bc521ace:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    3e214e0bcac34681bfb1987c96bb68ef:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    e9ca92a58a2d46fc87d4355f4831e961:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    16b3083df86246b9a9b29617fc7dbf0c:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    5797af3caad9414ca518c430c711309f:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    5ebc1ac7a7d74b918edaefefcfcff4a2:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    2fce378634764c159153ce7ebd65877a:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    8a39d28af1704ffe8cc89c179a486f05:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    1ff9f6554c41442c9ae7d890ade43dc2:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    54cdf6d26c7a4b05bcb22861458c1eaa:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    8d2bede6f6cb469792f91424b665a7b7:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    39ed567330354e108c6c33f1f68f4a42:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    ec42a52233334fed94740b923e427e60:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    cca22f5c450a493699ad807182e66f6f:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    f794410da207455c9980bb1971acf4b3:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    afdf6ca7896543a49f0c780f024bf116:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    a1c3c923534b4476a9dbea34773c21a9:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    4395382cdeaf4ebfba6a33eb449cd31b:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    b99ac12f2f564c35b5d128ea9f68f74c:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    7735167c6c4e46828fcfcc53f4a6fdfe:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    bc89b8a46b234a5bbe1173572e1ff724:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    44c2a1d9e68043968d2d015d921e6d95:
      title: The Song of the Vajra
      parent: Songs
    9625203b95344bd7824790b2853d4914:
      title: A Song in Six Verses
      parent: Songs
    87a7f76e94b94a0b8c21b8d7eace3294:
      title: Song of Experiential Certainty
      parent: Songs
    57a7df43d46944b4af703fb357cf58e4:
      title: Spontaneously Written Song of Experience
      parent: Songs
    9e3a41ae43c84eb0a01172ca3227325e:
      title: In This Pure Awareness
      parent: Songs
    d368c60caaac41f5af12326ba6bef171:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    7002886c51d54f6b8e2034e2ce133a38:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    79ef06a46e6345139902342b66dc3e98:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:31.990106'
last_modified_at: '2022-03-01T03:36:31.990109'
